### ISSUE TITLE
Add a copy of the MIT license in the repository

### ISSUE THREAD

**Issue by Calinou** [VicentGJ/Water_Temple_Godot-Demo#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by VicentGJ** [comment]
Ok, solved the issue, sorry for the mistake.

**Comment by Calinou** [comment]
Thanks! The asset is now approved: https://godotengine.org/asset-library/asset/489
